### ISSUE TITLE
[Dashboards & Widgets]

### ISSUE THREAD

**Issue by weedkiller** [phucan1108/letportal#52]
Hello how can we do dashboards and widgets easily as partials or tag helpers.
How to scaffold quickly
How to do Master Pages

**Comment by phucan1108** [comment]
Hi,

These features aren't in my plan. I am still considering to make the dashboard and widget by user's profile, but it is a huge effort. The only way to add new widget in the dashboard is assigning App to Role permission. I will let you know when I put them in the plan.

Also, a scaffold quickly means here? Basically, the idea is just helping a developer to parse the query (SELECT clause or Mongo Query) to the reflecting control (ex: the field data is number, so the control will be Number Control, Datetime will be DatePicker). You can use this way to construct a Standard Form, Dynamic List, Tree, Chart. 

For Master Page, I still don't have any idea for that one. It might be complexity meanwhile I just want it as a small platform for small team, small department.

Regards

**Comment by weedkiller** [comment]
Hey thanks for the response, I was only sharing suggestions, here are the codes to speed it up

- [ ] Dashboard Widgets: you can incorporate some from [Tuxboard](https://github.com/jdanylko/Tuxboard)
- [ ] Scaffold: Just T4 templates to scaffold them like https://github.com/polterguy/magic 
- [ ] Master-Details (two grids): https://demo.aspnetawesome.com/MasterDetailCrudDemo

**Comment by phucan1108** [comment]
Hi,

Thanks for your comment, it is very nice. 1st and 2nd point, I am considering how to integrate or implementing these features. For 3rd point, you can setup the same with LET. I have already tested and verified that but I didn't write the document for the scenario 😯  . I can draft the setup below:

1. Create one standard form (detail) and one dynamic list (master)
2. Put them together in one page (first is master and second is detail)
3. Set 'data' in the page is triggered by '!!queryparams.childid' to fetch detail data.
4. Back to dynamic list, set Edit button with route param such as 'page/master?childid={{data.id}}'
5. Test 🤗 
6. Note: Also you can set  'Create' button in detail is visible by '!!queryparams.create' , in master you add one 'Create' Outside with route 'page/master?create=true'. To render the detail section in case user clicks on 'Create' or 'Edit' in Master, just type ''!!queryparams.create || !!queryparams.childid' in 'Rendered' field in the section builder.

Both master and detail stay in the same page, and the data will be transit via queryparams.

Regards
