### ISSUE TITLE
Asp Identity & Roles with .NET 5 core and Ang 11/12

### ISSUE THREAD

**Issue by weedkiller** [phucan1108/letportal#56]
hello great template can we get an update on this

**Comment by weedkiller** [comment]
thanks. can you add asp claims also show samples or use of async pipes

**Comment by phucan1108** [comment]
> 
> 
> thanks. can you add asp claims also show samples or use of async pipes

What do you mean 'add asp claims' ? Basically, LET Portal is using custom claims itself based on Identity, not Identity Server 4. For 'async pipes', could you mean apply 'async' to MongoDB Pipeline?
